/**
 * Automile API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: v1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.automile.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.util.Objects;


/**
 * TripDetailModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-11T22:20:35.822+02:00")
public class TripDetailModel {
    @SerializedName("TripId")
    private Integer tripId = null;

    @SerializedName("IMEI")
    private String IMEI = null;

    @SerializedName("TripStartDateTime")
    private DateTime tripStartDateTime = null;

    @SerializedName("TripStartTimeZone")
    private Integer tripStartTimeZone = null;

    @SerializedName("TripStartODOMeter")
    private Integer tripStartODOMeter = null;

    @SerializedName("TripNumber")
    private Integer tripNumber = null;

    @SerializedName("NumberOfSupportedPIDs")
    private byte[] numberOfSupportedPIDs = null;

    @SerializedName("VehicleIdentificationNumber")
    private String vehicleIdentificationNumber = null;

    @SerializedName("VechicleProtocol")
    private String vechicleProtocol = null;

    @SerializedName("TripEndDateTime")
    private DateTime tripEndDateTime = null;

    @SerializedName("TripEndTimeZone")
    private Integer tripEndTimeZone = null;

    @SerializedName("TripEndODOMeter")
    private Integer tripEndODOMeter = null;

    @SerializedName("TripStartFormattedAddress")
    private String tripStartFormattedAddress = null;

    @SerializedName("TripEndFormattedAddress")
    private String tripEndFormattedAddress = null;

    @SerializedName("TripStartCustomAddress")
    private String tripStartCustomAddress = null;

    @SerializedName("TripEndCustomAddress")
    private String tripEndCustomAddress = null;
    @SerializedName("TripType")
    private TripTypeEnum tripType = null;
    @SerializedName("TripTags")
    private String tripTags = null;
    @SerializedName("VehicleId")
    private Integer vehicleId = null;
    @SerializedName("FuelInLiters")
    private Double fuelInLiters = null;
    @SerializedName("TripLengthInKilometers")
    private Double tripLengthInKilometers = null;
    @SerializedName("TripLengthInMinutes")
    private Integer tripLengthInMinutes = null;
    @SerializedName("IdleTimeInSecondsAllTrip")
    private Integer idleTimeInSecondsAllTrip = null;
    @SerializedName("IdleTimeInSecondsFromStart")
    private Integer idleTimeInSecondsFromStart = null;
    @SerializedName("IdleRPMMax")
    private Integer idleRPMMax = null;
    @SerializedName("MaxSpeed")
    private byte[] maxSpeed = null;
    @SerializedName("MaxRPM")
    private Integer maxRPM = null;
    @SerializedName("CO2EmissionInGrams")
    private Double cO2EmissionInGrams = null;
    @SerializedName("OdometerInKilometersAfterTripEnded")
    private Double odometerInKilometersAfterTripEnded = null;
    @SerializedName("AverageSpeedInKilometersPerHour")
    private Double averageSpeedInKilometersPerHour = null;
    @SerializedName("TripStartOutsideTemperatureInCelsius")
    private Double tripStartOutsideTemperatureInCelsius = null;
    @SerializedName("DriverContactId")
    private Integer driverContactId = null;
    @SerializedName("HasDrivingEvents")
    private Boolean hasDrivingEvents = null;
    @SerializedName("CustomCategory")
    private String customCategory = null;
    @SerializedName("HideStartRoute")
    private Boolean hideStartRoute = null;
    @SerializedName("HideEndRoute")
    private Boolean hideEndRoute = null;

    public TripDetailModel tripId(Integer tripId) {
        this.tripId = tripId;
        return this;
    }

    /**
     * Get tripId
     * @return tripId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripId() {
        return tripId;
    }

    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }

    public TripDetailModel IMEI(String IMEI) {
        this.IMEI = IMEI;
        return this;
    }

    /**
     * Get IMEI
     * @return IMEI
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getIMEI() {
        return IMEI;
    }

    public void setIMEI(String IMEI) {
        this.IMEI = IMEI;
    }

    public TripDetailModel tripStartDateTime(DateTime tripStartDateTime) {
        this.tripStartDateTime = tripStartDateTime;
        return this;
    }

    /**
     * Get tripStartDateTime
     * @return tripStartDateTime
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getTripStartDateTime() {
        return tripStartDateTime;
    }

    public void setTripStartDateTime(DateTime tripStartDateTime) {
        this.tripStartDateTime = tripStartDateTime;
    }

    public TripDetailModel tripStartTimeZone(Integer tripStartTimeZone) {
        this.tripStartTimeZone = tripStartTimeZone;
        return this;
    }

    /**
     * Get tripStartTimeZone
     * @return tripStartTimeZone
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripStartTimeZone() {
        return tripStartTimeZone;
    }

    public void setTripStartTimeZone(Integer tripStartTimeZone) {
        this.tripStartTimeZone = tripStartTimeZone;
    }

    public TripDetailModel tripStartODOMeter(Integer tripStartODOMeter) {
        this.tripStartODOMeter = tripStartODOMeter;
        return this;
    }

    /**
     * Get tripStartODOMeter
     * @return tripStartODOMeter
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripStartODOMeter() {
        return tripStartODOMeter;
    }

    public void setTripStartODOMeter(Integer tripStartODOMeter) {
        this.tripStartODOMeter = tripStartODOMeter;
    }

    public TripDetailModel tripNumber(Integer tripNumber) {
        this.tripNumber = tripNumber;
        return this;
    }

    /**
     * Get tripNumber
     * @return tripNumber
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripNumber() {
        return tripNumber;
    }

    public void setTripNumber(Integer tripNumber) {
        this.tripNumber = tripNumber;
    }

    public TripDetailModel numberOfSupportedPIDs(byte[] numberOfSupportedPIDs) {
        this.numberOfSupportedPIDs = numberOfSupportedPIDs;
        return this;
    }

    /**
     * Get numberOfSupportedPIDs
     * @return numberOfSupportedPIDs
     **/
    @ApiModelProperty(example = "null", value = "")
    public byte[] getNumberOfSupportedPIDs() {
        return numberOfSupportedPIDs;
    }

    public void setNumberOfSupportedPIDs(byte[] numberOfSupportedPIDs) {
        this.numberOfSupportedPIDs = numberOfSupportedPIDs;
    }

    public TripDetailModel vehicleIdentificationNumber(String vehicleIdentificationNumber) {
        this.vehicleIdentificationNumber = vehicleIdentificationNumber;
        return this;
    }

    /**
     * Get vehicleIdentificationNumber
     * @return vehicleIdentificationNumber
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getVehicleIdentificationNumber() {
        return vehicleIdentificationNumber;
    }

    public void setVehicleIdentificationNumber(String vehicleIdentificationNumber) {
        this.vehicleIdentificationNumber = vehicleIdentificationNumber;
    }

    public TripDetailModel vechicleProtocol(String vechicleProtocol) {
        this.vechicleProtocol = vechicleProtocol;
        return this;
    }

    /**
     * Get vechicleProtocol
     * @return vechicleProtocol
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getVechicleProtocol() {
        return vechicleProtocol;
    }

    public void setVechicleProtocol(String vechicleProtocol) {
        this.vechicleProtocol = vechicleProtocol;
    }

    public TripDetailModel tripEndDateTime(DateTime tripEndDateTime) {
        this.tripEndDateTime = tripEndDateTime;
        return this;
    }

    /**
     * Get tripEndDateTime
     * @return tripEndDateTime
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getTripEndDateTime() {
        return tripEndDateTime;
    }

    public void setTripEndDateTime(DateTime tripEndDateTime) {
        this.tripEndDateTime = tripEndDateTime;
    }

    public TripDetailModel tripEndTimeZone(Integer tripEndTimeZone) {
        this.tripEndTimeZone = tripEndTimeZone;
        return this;
    }

    /**
     * Get tripEndTimeZone
     * @return tripEndTimeZone
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripEndTimeZone() {
        return tripEndTimeZone;
    }

    public void setTripEndTimeZone(Integer tripEndTimeZone) {
        this.tripEndTimeZone = tripEndTimeZone;
    }

    public TripDetailModel tripEndODOMeter(Integer tripEndODOMeter) {
        this.tripEndODOMeter = tripEndODOMeter;
        return this;
    }

    /**
     * Get tripEndODOMeter
     * @return tripEndODOMeter
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripEndODOMeter() {
        return tripEndODOMeter;
    }

    public void setTripEndODOMeter(Integer tripEndODOMeter) {
        this.tripEndODOMeter = tripEndODOMeter;
    }

    public TripDetailModel tripStartFormattedAddress(String tripStartFormattedAddress) {
        this.tripStartFormattedAddress = tripStartFormattedAddress;
        return this;
    }

    /**
     * Get tripStartFormattedAddress
     * @return tripStartFormattedAddress
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTripStartFormattedAddress() {
        return tripStartFormattedAddress;
    }

    public void setTripStartFormattedAddress(String tripStartFormattedAddress) {
        this.tripStartFormattedAddress = tripStartFormattedAddress;
    }

    public TripDetailModel tripEndFormattedAddress(String tripEndFormattedAddress) {
        this.tripEndFormattedAddress = tripEndFormattedAddress;
        return this;
    }

    /**
     * Get tripEndFormattedAddress
     * @return tripEndFormattedAddress
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTripEndFormattedAddress() {
        return tripEndFormattedAddress;
    }

    public void setTripEndFormattedAddress(String tripEndFormattedAddress) {
        this.tripEndFormattedAddress = tripEndFormattedAddress;
    }

    public TripDetailModel tripStartCustomAddress(String tripStartCustomAddress) {
        this.tripStartCustomAddress = tripStartCustomAddress;
        return this;
    }

    /**
     * Get tripStartCustomAddress
     * @return tripStartCustomAddress
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTripStartCustomAddress() {
        return tripStartCustomAddress;
    }

    public void setTripStartCustomAddress(String tripStartCustomAddress) {
        this.tripStartCustomAddress = tripStartCustomAddress;
    }

    public TripDetailModel tripEndCustomAddress(String tripEndCustomAddress) {
        this.tripEndCustomAddress = tripEndCustomAddress;
        return this;
    }

    /**
     * Get tripEndCustomAddress
     * @return tripEndCustomAddress
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTripEndCustomAddress() {
        return tripEndCustomAddress;
    }

    public void setTripEndCustomAddress(String tripEndCustomAddress) {
        this.tripEndCustomAddress = tripEndCustomAddress;
    }

    public TripDetailModel tripType(TripTypeEnum tripType) {
        this.tripType = tripType;
        return this;
    }

    /**
     * Get tripType
     * @return tripType
     **/
    @ApiModelProperty(example = "null", value = "")
    public TripTypeEnum getTripType() {
        return tripType;
    }

    public void setTripType(TripTypeEnum tripType) {
        this.tripType = tripType;
    }

    public TripDetailModel tripTags(String tripTags) {
        this.tripTags = tripTags;
        return this;
    }

    /**
     * Get tripTags
     * @return tripTags
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTripTags() {
        return tripTags;
    }

    public void setTripTags(String tripTags) {
        this.tripTags = tripTags;
    }

    public TripDetailModel vehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
        return this;
    }

    /**
     * Get vehicleId
     * @return vehicleId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    public TripDetailModel fuelInLiters(Double fuelInLiters) {
        this.fuelInLiters = fuelInLiters;
        return this;
    }

    /**
     * Get fuelInLiters
     * @return fuelInLiters
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getFuelInLiters() {
        return fuelInLiters;
    }

    public void setFuelInLiters(Double fuelInLiters) {
        this.fuelInLiters = fuelInLiters;
    }

    public TripDetailModel tripLengthInKilometers(Double tripLengthInKilometers) {
        this.tripLengthInKilometers = tripLengthInKilometers;
        return this;
    }

    /**
     * Get tripLengthInKilometers
     * @return tripLengthInKilometers
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getTripLengthInKilometers() {
        return tripLengthInKilometers;
    }

    public void setTripLengthInKilometers(Double tripLengthInKilometers) {
        this.tripLengthInKilometers = tripLengthInKilometers;
    }

    public TripDetailModel tripLengthInMinutes(Integer tripLengthInMinutes) {
        this.tripLengthInMinutes = tripLengthInMinutes;
        return this;
    }

    /**
     * Get tripLengthInMinutes
     * @return tripLengthInMinutes
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTripLengthInMinutes() {
        return tripLengthInMinutes;
    }

    public void setTripLengthInMinutes(Integer tripLengthInMinutes) {
        this.tripLengthInMinutes = tripLengthInMinutes;
    }

    public TripDetailModel idleTimeInSecondsAllTrip(Integer idleTimeInSecondsAllTrip) {
        this.idleTimeInSecondsAllTrip = idleTimeInSecondsAllTrip;
        return this;
    }

    /**
     * Get idleTimeInSecondsAllTrip
     * @return idleTimeInSecondsAllTrip
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getIdleTimeInSecondsAllTrip() {
        return idleTimeInSecondsAllTrip;
    }

    public void setIdleTimeInSecondsAllTrip(Integer idleTimeInSecondsAllTrip) {
        this.idleTimeInSecondsAllTrip = idleTimeInSecondsAllTrip;
    }

    public TripDetailModel idleTimeInSecondsFromStart(Integer idleTimeInSecondsFromStart) {
        this.idleTimeInSecondsFromStart = idleTimeInSecondsFromStart;
        return this;
    }

    /**
     * Get idleTimeInSecondsFromStart
     * @return idleTimeInSecondsFromStart
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getIdleTimeInSecondsFromStart() {
        return idleTimeInSecondsFromStart;
    }

    public void setIdleTimeInSecondsFromStart(Integer idleTimeInSecondsFromStart) {
        this.idleTimeInSecondsFromStart = idleTimeInSecondsFromStart;
    }

    public TripDetailModel idleRPMMax(Integer idleRPMMax) {
        this.idleRPMMax = idleRPMMax;
        return this;
    }

    /**
     * Get idleRPMMax
     * @return idleRPMMax
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getIdleRPMMax() {
        return idleRPMMax;
    }

    public void setIdleRPMMax(Integer idleRPMMax) {
        this.idleRPMMax = idleRPMMax;
    }

    public TripDetailModel maxSpeed(byte[] maxSpeed) {
        this.maxSpeed = maxSpeed;
        return this;
    }

    /**
     * Get maxSpeed
     * @return maxSpeed
     **/
    @ApiModelProperty(example = "null", value = "")
    public byte[] getMaxSpeed() {
        return maxSpeed;
    }

    public void setMaxSpeed(byte[] maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    public TripDetailModel maxRPM(Integer maxRPM) {
        this.maxRPM = maxRPM;
        return this;
    }

    /**
     * Get maxRPM
     * @return maxRPM
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getMaxRPM() {
        return maxRPM;
    }

    public void setMaxRPM(Integer maxRPM) {
        this.maxRPM = maxRPM;
    }

    public TripDetailModel cO2EmissionInGrams(Double cO2EmissionInGrams) {
        this.cO2EmissionInGrams = cO2EmissionInGrams;
        return this;
    }

    /**
     * Get cO2EmissionInGrams
     * @return cO2EmissionInGrams
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getCO2EmissionInGrams() {
        return cO2EmissionInGrams;
    }

    public void setCO2EmissionInGrams(Double cO2EmissionInGrams) {
        this.cO2EmissionInGrams = cO2EmissionInGrams;
    }

    public TripDetailModel odometerInKilometersAfterTripEnded(Double odometerInKilometersAfterTripEnded) {
        this.odometerInKilometersAfterTripEnded = odometerInKilometersAfterTripEnded;
        return this;
    }

    /**
     * Get odometerInKilometersAfterTripEnded
     * @return odometerInKilometersAfterTripEnded
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getOdometerInKilometersAfterTripEnded() {
        return odometerInKilometersAfterTripEnded;
    }

    public void setOdometerInKilometersAfterTripEnded(Double odometerInKilometersAfterTripEnded) {
        this.odometerInKilometersAfterTripEnded = odometerInKilometersAfterTripEnded;
    }

    public TripDetailModel averageSpeedInKilometersPerHour(Double averageSpeedInKilometersPerHour) {
        this.averageSpeedInKilometersPerHour = averageSpeedInKilometersPerHour;
        return this;
    }

    /**
     * Get averageSpeedInKilometersPerHour
     * @return averageSpeedInKilometersPerHour
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getAverageSpeedInKilometersPerHour() {
        return averageSpeedInKilometersPerHour;
    }

    public void setAverageSpeedInKilometersPerHour(Double averageSpeedInKilometersPerHour) {
        this.averageSpeedInKilometersPerHour = averageSpeedInKilometersPerHour;
    }

    public TripDetailModel tripStartOutsideTemperatureInCelsius(Double tripStartOutsideTemperatureInCelsius) {
        this.tripStartOutsideTemperatureInCelsius = tripStartOutsideTemperatureInCelsius;
        return this;
    }

    /**
     * Get tripStartOutsideTemperatureInCelsius
     * @return tripStartOutsideTemperatureInCelsius
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getTripStartOutsideTemperatureInCelsius() {
        return tripStartOutsideTemperatureInCelsius;
    }

    public void setTripStartOutsideTemperatureInCelsius(Double tripStartOutsideTemperatureInCelsius) {
        this.tripStartOutsideTemperatureInCelsius = tripStartOutsideTemperatureInCelsius;
    }

    public TripDetailModel driverContactId(Integer driverContactId) {
        this.driverContactId = driverContactId;
        return this;
    }

    /**
     * Get driverContactId
     * @return driverContactId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getDriverContactId() {
        return driverContactId;
    }

    public void setDriverContactId(Integer driverContactId) {
        this.driverContactId = driverContactId;
    }

    public TripDetailModel hasDrivingEvents(Boolean hasDrivingEvents) {
        this.hasDrivingEvents = hasDrivingEvents;
        return this;
    }

    /**
     * Get hasDrivingEvents
     * @return hasDrivingEvents
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getHasDrivingEvents() {
        return hasDrivingEvents;
    }

    public void setHasDrivingEvents(Boolean hasDrivingEvents) {
        this.hasDrivingEvents = hasDrivingEvents;
    }

    public TripDetailModel customCategory(String customCategory) {
        this.customCategory = customCategory;
        return this;
    }

    /**
     * Get customCategory
     * @return customCategory
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCustomCategory() {
        return customCategory;
    }

    public void setCustomCategory(String customCategory) {
        this.customCategory = customCategory;
    }

    public TripDetailModel hideStartRoute(Boolean hideStartRoute) {
        this.hideStartRoute = hideStartRoute;
        return this;
    }

    /**
     * Get hideStartRoute
     * @return hideStartRoute
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getHideStartRoute() {
        return hideStartRoute;
    }

    public void setHideStartRoute(Boolean hideStartRoute) {
        this.hideStartRoute = hideStartRoute;
    }

    public TripDetailModel hideEndRoute(Boolean hideEndRoute) {
        this.hideEndRoute = hideEndRoute;
        return this;
    }

    /**
     * Get hideEndRoute
     * @return hideEndRoute
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getHideEndRoute() {
        return hideEndRoute;
    }

    public void setHideEndRoute(Boolean hideEndRoute) {
        this.hideEndRoute = hideEndRoute;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TripDetailModel tripDetailModel = (TripDetailModel) o;
        return Objects.equals(this.tripId, tripDetailModel.tripId) &&
                Objects.equals(this.IMEI, tripDetailModel.IMEI) &&
                Objects.equals(this.tripStartDateTime, tripDetailModel.tripStartDateTime) &&
                Objects.equals(this.tripStartTimeZone, tripDetailModel.tripStartTimeZone) &&
                Objects.equals(this.tripStartODOMeter, tripDetailModel.tripStartODOMeter) &&
                Objects.equals(this.tripNumber, tripDetailModel.tripNumber) &&
                Objects.equals(this.numberOfSupportedPIDs, tripDetailModel.numberOfSupportedPIDs) &&
                Objects.equals(this.vehicleIdentificationNumber, tripDetailModel.vehicleIdentificationNumber) &&
                Objects.equals(this.vechicleProtocol, tripDetailModel.vechicleProtocol) &&
                Objects.equals(this.tripEndDateTime, tripDetailModel.tripEndDateTime) &&
                Objects.equals(this.tripEndTimeZone, tripDetailModel.tripEndTimeZone) &&
                Objects.equals(this.tripEndODOMeter, tripDetailModel.tripEndODOMeter) &&
                Objects.equals(this.tripStartFormattedAddress, tripDetailModel.tripStartFormattedAddress) &&
                Objects.equals(this.tripEndFormattedAddress, tripDetailModel.tripEndFormattedAddress) &&
                Objects.equals(this.tripStartCustomAddress, tripDetailModel.tripStartCustomAddress) &&
                Objects.equals(this.tripEndCustomAddress, tripDetailModel.tripEndCustomAddress) &&
                Objects.equals(this.tripType, tripDetailModel.tripType) &&
                Objects.equals(this.tripTags, tripDetailModel.tripTags) &&
                Objects.equals(this.vehicleId, tripDetailModel.vehicleId) &&
                Objects.equals(this.fuelInLiters, tripDetailModel.fuelInLiters) &&
                Objects.equals(this.tripLengthInKilometers, tripDetailModel.tripLengthInKilometers) &&
                Objects.equals(this.tripLengthInMinutes, tripDetailModel.tripLengthInMinutes) &&
                Objects.equals(this.idleTimeInSecondsAllTrip, tripDetailModel.idleTimeInSecondsAllTrip) &&
                Objects.equals(this.idleTimeInSecondsFromStart, tripDetailModel.idleTimeInSecondsFromStart) &&
                Objects.equals(this.idleRPMMax, tripDetailModel.idleRPMMax) &&
                Objects.equals(this.maxSpeed, tripDetailModel.maxSpeed) &&
                Objects.equals(this.maxRPM, tripDetailModel.maxRPM) &&
                Objects.equals(this.cO2EmissionInGrams, tripDetailModel.cO2EmissionInGrams) &&
                Objects.equals(this.odometerInKilometersAfterTripEnded, tripDetailModel.odometerInKilometersAfterTripEnded) &&
                Objects.equals(this.averageSpeedInKilometersPerHour, tripDetailModel.averageSpeedInKilometersPerHour) &&
                Objects.equals(this.tripStartOutsideTemperatureInCelsius, tripDetailModel.tripStartOutsideTemperatureInCelsius) &&
                Objects.equals(this.driverContactId, tripDetailModel.driverContactId) &&
                Objects.equals(this.hasDrivingEvents, tripDetailModel.hasDrivingEvents) &&
                Objects.equals(this.customCategory, tripDetailModel.customCategory) &&
                Objects.equals(this.hideStartRoute, tripDetailModel.hideStartRoute) &&
                Objects.equals(this.hideEndRoute, tripDetailModel.hideEndRoute);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tripId, IMEI, tripStartDateTime, tripStartTimeZone, tripStartODOMeter, tripNumber, numberOfSupportedPIDs, vehicleIdentificationNumber, vechicleProtocol, tripEndDateTime, tripEndTimeZone, tripEndODOMeter, tripStartFormattedAddress, tripEndFormattedAddress, tripStartCustomAddress, tripEndCustomAddress, tripType, tripTags, vehicleId, fuelInLiters, tripLengthInKilometers, tripLengthInMinutes, idleTimeInSecondsAllTrip, idleTimeInSecondsFromStart, idleRPMMax, maxSpeed, maxRPM, cO2EmissionInGrams, odometerInKilometersAfterTripEnded, averageSpeedInKilometersPerHour, tripStartOutsideTemperatureInCelsius, driverContactId, hasDrivingEvents, customCategory, hideStartRoute, hideEndRoute);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TripDetailModel {\n");

        sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
        sb.append("    IMEI: ").append(toIndentedString(IMEI)).append("\n");
        sb.append("    tripStartDateTime: ").append(toIndentedString(tripStartDateTime)).append("\n");
        sb.append("    tripStartTimeZone: ").append(toIndentedString(tripStartTimeZone)).append("\n");
        sb.append("    tripStartODOMeter: ").append(toIndentedString(tripStartODOMeter)).append("\n");
        sb.append("    tripNumber: ").append(toIndentedString(tripNumber)).append("\n");
        sb.append("    numberOfSupportedPIDs: ").append(toIndentedString(numberOfSupportedPIDs)).append("\n");
        sb.append("    vehicleIdentificationNumber: ").append(toIndentedString(vehicleIdentificationNumber)).append("\n");
        sb.append("    vechicleProtocol: ").append(toIndentedString(vechicleProtocol)).append("\n");
        sb.append("    tripEndDateTime: ").append(toIndentedString(tripEndDateTime)).append("\n");
        sb.append("    tripEndTimeZone: ").append(toIndentedString(tripEndTimeZone)).append("\n");
        sb.append("    tripEndODOMeter: ").append(toIndentedString(tripEndODOMeter)).append("\n");
        sb.append("    tripStartFormattedAddress: ").append(toIndentedString(tripStartFormattedAddress)).append("\n");
        sb.append("    tripEndFormattedAddress: ").append(toIndentedString(tripEndFormattedAddress)).append("\n");
        sb.append("    tripStartCustomAddress: ").append(toIndentedString(tripStartCustomAddress)).append("\n");
        sb.append("    tripEndCustomAddress: ").append(toIndentedString(tripEndCustomAddress)).append("\n");
        sb.append("    tripType: ").append(toIndentedString(tripType)).append("\n");
        sb.append("    tripTags: ").append(toIndentedString(tripTags)).append("\n");
        sb.append("    vehicleId: ").append(toIndentedString(vehicleId)).append("\n");
        sb.append("    fuelInLiters: ").append(toIndentedString(fuelInLiters)).append("\n");
        sb.append("    tripLengthInKilometers: ").append(toIndentedString(tripLengthInKilometers)).append("\n");
        sb.append("    tripLengthInMinutes: ").append(toIndentedString(tripLengthInMinutes)).append("\n");
        sb.append("    idleTimeInSecondsAllTrip: ").append(toIndentedString(idleTimeInSecondsAllTrip)).append("\n");
        sb.append("    idleTimeInSecondsFromStart: ").append(toIndentedString(idleTimeInSecondsFromStart)).append("\n");
        sb.append("    idleRPMMax: ").append(toIndentedString(idleRPMMax)).append("\n");
        sb.append("    maxSpeed: ").append(toIndentedString(maxSpeed)).append("\n");
        sb.append("    maxRPM: ").append(toIndentedString(maxRPM)).append("\n");
        sb.append("    cO2EmissionInGrams: ").append(toIndentedString(cO2EmissionInGrams)).append("\n");
        sb.append("    odometerInKilometersAfterTripEnded: ").append(toIndentedString(odometerInKilometersAfterTripEnded)).append("\n");
        sb.append("    averageSpeedInKilometersPerHour: ").append(toIndentedString(averageSpeedInKilometersPerHour)).append("\n");
        sb.append("    tripStartOutsideTemperatureInCelsius: ").append(toIndentedString(tripStartOutsideTemperatureInCelsius)).append("\n");
        sb.append("    driverContactId: ").append(toIndentedString(driverContactId)).append("\n");
        sb.append("    hasDrivingEvents: ").append(toIndentedString(hasDrivingEvents)).append("\n");
        sb.append("    customCategory: ").append(toIndentedString(customCategory)).append("\n");
        sb.append("    hideStartRoute: ").append(toIndentedString(hideStartRoute)).append("\n");
        sb.append("    hideEndRoute: ").append(toIndentedString(hideEndRoute)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets tripType
     */
    public enum TripTypeEnum {
        @SerializedName("0")
        NUMBER_0(0),

        @SerializedName("1")
        NUMBER_1(1),

        @SerializedName("2")
        NUMBER_2(2),

        @SerializedName("3")
        NUMBER_3(3);

        private Integer value;

        TripTypeEnum(Integer value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }
}

