/**
 * Automile API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: v1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.automile.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * TripSummaryReportModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-11T22:20:35.822+02:00")
public class TripSummaryReportModel {
    @SerializedName("ReportStartPeriod")
    private Integer reportStartPeriod = null;

    @SerializedName("ReportEndPeriod")
    private Integer reportEndPeriod = null;

    @SerializedName("VehicleId")
    private Integer vehicleId = null;
    @SerializedName("TripType")
    private TripTypeEnum tripType = null;
    @SerializedName("DistanceInKilometers")
    private Double distanceInKilometers = null;
    @SerializedName("TravelTimeInMinutes")
    private Integer travelTimeInMinutes = null;
    @SerializedName("FuelInLiters")
    private Double fuelInLiters = null;

    public TripSummaryReportModel reportStartPeriod(Integer reportStartPeriod) {
        this.reportStartPeriod = reportStartPeriod;
        return this;
    }

    /**
     * Get reportStartPeriod
     * @return reportStartPeriod
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getReportStartPeriod() {
        return reportStartPeriod;
    }

    public void setReportStartPeriod(Integer reportStartPeriod) {
        this.reportStartPeriod = reportStartPeriod;
    }

    public TripSummaryReportModel reportEndPeriod(Integer reportEndPeriod) {
        this.reportEndPeriod = reportEndPeriod;
        return this;
    }

    /**
     * Get reportEndPeriod
     * @return reportEndPeriod
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getReportEndPeriod() {
        return reportEndPeriod;
    }

    public void setReportEndPeriod(Integer reportEndPeriod) {
        this.reportEndPeriod = reportEndPeriod;
    }

    public TripSummaryReportModel vehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
        return this;
    }

    /**
     * Get vehicleId
     * @return vehicleId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    public TripSummaryReportModel tripType(TripTypeEnum tripType) {
        this.tripType = tripType;
        return this;
    }

    /**
     * Get tripType
     * @return tripType
     **/
    @ApiModelProperty(example = "null", value = "")
    public TripTypeEnum getTripType() {
        return tripType;
    }

    public void setTripType(TripTypeEnum tripType) {
        this.tripType = tripType;
    }

    public TripSummaryReportModel distanceInKilometers(Double distanceInKilometers) {
        this.distanceInKilometers = distanceInKilometers;
        return this;
    }

    /**
     * Get distanceInKilometers
     * @return distanceInKilometers
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getDistanceInKilometers() {
        return distanceInKilometers;
    }

    public void setDistanceInKilometers(Double distanceInKilometers) {
        this.distanceInKilometers = distanceInKilometers;
    }

    public TripSummaryReportModel travelTimeInMinutes(Integer travelTimeInMinutes) {
        this.travelTimeInMinutes = travelTimeInMinutes;
        return this;
    }

    /**
     * Get travelTimeInMinutes
     * @return travelTimeInMinutes
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getTravelTimeInMinutes() {
        return travelTimeInMinutes;
    }

    public void setTravelTimeInMinutes(Integer travelTimeInMinutes) {
        this.travelTimeInMinutes = travelTimeInMinutes;
    }

    public TripSummaryReportModel fuelInLiters(Double fuelInLiters) {
        this.fuelInLiters = fuelInLiters;
        return this;
    }

    /**
     * Get fuelInLiters
     * @return fuelInLiters
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getFuelInLiters() {
        return fuelInLiters;
    }

    public void setFuelInLiters(Double fuelInLiters) {
        this.fuelInLiters = fuelInLiters;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TripSummaryReportModel tripSummaryReportModel = (TripSummaryReportModel) o;
        return Objects.equals(this.reportStartPeriod, tripSummaryReportModel.reportStartPeriod) &&
                Objects.equals(this.reportEndPeriod, tripSummaryReportModel.reportEndPeriod) &&
                Objects.equals(this.vehicleId, tripSummaryReportModel.vehicleId) &&
                Objects.equals(this.tripType, tripSummaryReportModel.tripType) &&
                Objects.equals(this.distanceInKilometers, tripSummaryReportModel.distanceInKilometers) &&
                Objects.equals(this.travelTimeInMinutes, tripSummaryReportModel.travelTimeInMinutes) &&
                Objects.equals(this.fuelInLiters, tripSummaryReportModel.fuelInLiters);
    }

    @Override
    public int hashCode() {
        return Objects.hash(reportStartPeriod, reportEndPeriod, vehicleId, tripType, distanceInKilometers, travelTimeInMinutes, fuelInLiters);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TripSummaryReportModel {\n");

        sb.append("    reportStartPeriod: ").append(toIndentedString(reportStartPeriod)).append("\n");
        sb.append("    reportEndPeriod: ").append(toIndentedString(reportEndPeriod)).append("\n");
        sb.append("    vehicleId: ").append(toIndentedString(vehicleId)).append("\n");
        sb.append("    tripType: ").append(toIndentedString(tripType)).append("\n");
        sb.append("    distanceInKilometers: ").append(toIndentedString(distanceInKilometers)).append("\n");
        sb.append("    travelTimeInMinutes: ").append(toIndentedString(travelTimeInMinutes)).append("\n");
        sb.append("    fuelInLiters: ").append(toIndentedString(fuelInLiters)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets tripType
     */
    public enum TripTypeEnum {
        @SerializedName("0")
        NUMBER_0(0),

        @SerializedName("1")
        NUMBER_1(1),

        @SerializedName("2")
        NUMBER_2(2);

        private Integer value;

        TripTypeEnum(Integer value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }
}

